name = "Cyclops"
uuid = "d909977f-157f-4d80-91d6-6db50a32a137"
authors = ["JanHammarlund <hammarlund.jan@gmail.com> and contributors"]
version = "v1.0.0"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
