name = "Cyclops"
uuid = "d909977f-157f-4d80-91d6-6db50a32a137"
version = "0.1.0"
authors = ["JanHammarlund <hammarlund.jan@gmail.com> and contributors"]

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"

[compat]
CUDA = "5.9.2"
CairoMakie = "0.15.7"
Documenter = "1.16.1"
Flux = "0.16.5"
InteractiveUtils = "1.11.0"
Makie = "0.24.7"
ProgressMeter = "1.11.0"
Random = "1.11.0"
Statistics = "1.11.1"
cuDNN = "1.4.6"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
