name = "CYCLOPS"
uuid = "d909977f-157f-4d80-91d6-6db50a32a137"
version = "1.0.0-DEV"
authors = ["JanHammarlund <hammarlund.jan@gmail.com> and contributors"]

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"

[compat]
CUDA = "5.9.2"
Flux = "0.16.5"
Plots = "1.41.1"
ProgressMeter = "1.11.0"
Random = "1.11.0"
Statistics = "1.11.1"
cuDNN = "1.4.6"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
